apiVersion: v1
kind: Template
labels:
  template: fluentd-secure-forwarder
metadata:
  annotations:
    openshift.io/display-name: Fluentd Secure Forwarder
    tags: fluentd
  name: fluentd-secure-forwarder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
    namespace: ${NAMESPACE}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: fluentd-secure-forwarder:latest
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/clasohm/fluentd-secure-forwarder.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ruby:2.5
          namespace: openshift
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: secure-forwarder-cert
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
  spec:
    ports:
    - name: fluentd-secure-forwarder
      port: 24284
    selector:
      deploymentconfig: fluentd-secure-forwarder
- apiVersion: v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-openshift-logging
  spec:
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: openshift-logging
  podSelector: {}
  policyTypes:
      - Ingress
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
  data:
    splunk-hec-host: "input-prd-example.cloud.splunk.com"
    splunk-hec-port: "8088"
    splunk-hec-ssl-verify: "false"
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
  type: Opaque
  data:
    sf-shared-key: Q0hBTkdFTUU=
    splunk-hec-token: Q0hBTkdFTUU=
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      template: fluentd-secure-forwarder
    name: fluentd-secure-forwarder
  spec:
    replicas: 1
    selector:
      template: fluentd-secure-forwarder
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          template: fluentd-secure-forwarder
      spec:
        containers:
        - name: fluentd
          env:
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: SF_SHARED_KEY
            valueFrom:
              secretKeyRef:
                key: sf-shared-key
                name: fluentd-secure-forwarder
          - name: SPLUNK_HEC_HOST
            valueFrom:
              configMapKeyRef:
                key: splunk-hec-host
                name: fluentd-secure-forwarder
          - name: SPLUNK_HEC_PORT
            valueFrom:
              configMapKeyRef:
                key: splunk-hec-port
                name: fluentd-secure-forwarder
          - name: SPLUNK_HEC_SSL_VERIFY
            valueFrom:
              configMapKeyRef:
                key: splunk-hec-ssl-verify
                name: fluentd-secure-forwarder
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                key: splunk-hec-token
                name: fluentd-secure-forwarder
          image: docker-registry.default.svc:5000/${NAMESPACE}/logging-fluentd-splunk
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 24284
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 24284
            timeoutSeconds: 1
          volumeMounts:
            - name: fluent-certs
              mountPath: /etc/fluent/certs
              readOnly: true
        volumes:
          - name: fluent-certs
            secret:
              secretName: secure-forwarder-cert
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - fluentd
        from:
          kind: ImageStreamTag
          name: fluentd-secure-forwarder:latest
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The OpenShift Namespace to deploy to.
  displayName: Namespace
  name: NAMESPACE
